export interface Testimonial {
  id: string;
  name: string;
  profession?: string;
  treatment: string;
  content: string;
  rating: number;
  date: string;
  imageUrl?: string;
  videoUrl?: string;
}

export const testimonials: Testimonial[] = [
  {
    id: "1",
    name: "Άκης Σακελλαρίου",
    profession: "Ηθοποιός",
    treatment: "Πρόβλημα υγείας",
    content: "Ο ηθοποιός Άκης Σακελλαρίου μιλάει για το πρόβλημα υγείας",
    rating: 5,
    date: "2023-11-15",
    videoUrl: "Eqsq918L4KQ",
  },
  {
    id: "2",
    name: "Χάϊκ Γιαζιτζιάν",
    profession: "Συνθέτης και δεξιοτέχνης του ούτι",
    treatment: "Φυσικοθεραπεία",
    content: "Εξαιρετική εμπειρία με ολοκληρωμένη φυσικοθεραπευτική αντιμετώπιση",
    rating: 5,
    date: "2023-10-20",
    imageUrl: "/gallery/testimonials/outistas.jpg",
  },
  {
    id: "3",
    name: "Γιώργος Τσάμπρας",
    profession: "Δημοσιογράφος, Κοινωνιολόγος, Μουσικός Παραγωγός",
    treatment: "Ολιστική Αποκατάσταση",
    content: "Με τον φίλο Δημοσιογράφο, κοινωνιολόγο, μουσικό παραγωγό Γιώργο Τσάμπρα",
    rating: 5,
    date: "2023-09-10",
    imageUrl: "/gallery/testimonials/tsampras.jpg",
  },
  {
    id: "4",
    name: "Δήμητρα Τρυπάνη",
    profession: "Καθηγήτρια Μουσικής και Μουσικοκινητικής Αγωγής ΕΚΠΑ, Συνθέτρια",
    treatment: "PRP Θεραπεία",
    content: "Με την αγαπημένη αξιόλογη συνθέτρια Δήμητρα Τρυπάνη, Καθηγήτρια Μουσικής και Μουσικοκινητικής Αγωγής ΕΚΠΑ",
    rating: 5,
    date: "2023-08-25",
    imageUrl: "/gallery/testimonials/tripani.jpg",
  },
  {
    id: "5",
    name: "Γρηγόρης Βασίλας",
    profession: "Σολίστας - Δημιουργός - Δάσκαλος Μπουζουκιού",
    treatment: "Μεσοθεραπεία",
    content: "Με τον Γρηγόρη Βασίλα, Σολίστα - Δημιουργό - Δάσκαλο Μπουζουκιού",
    rating: 5,
    date: "2023-07-18",
    imageUrl: "/gallery/testimonials/vasila.jpg",
  },
  {
    id: "6",
    name: "Τένια Μακρή",
    profession: "Θεραπεύτρια Ψυχής και Συμβουλος Οικογένειας",
    treatment: "Βελονισμός",
    content: "Με την φίλη Θεραπεύτρια Ψυχής και Σύμβουλο Οικογένειας Τένια Μακρή",
    rating: 5,
    date: "2023-06-30",
    imageUrl: "/gallery/testimonials/img_4033.jpg",
  },
  {
    id: "7",
    name: "Κατερίνα Τσιρίδου",
    profession: "Τραγουδίστρια Ρεμπέτικου",
    treatment: "Κρουστικά Κύματα",
    content: "Με την τραγουδίστρια του Ρεμπέτικου Κατερίνα Τσιρίδου",
    rating: 5,
    date: "2023-05-22",
    imageUrl: "/gallery/testimonials/img_4242.jpg",
  },
  {
    id: "8",
    name: "Ψαραντώνης",
    profession: "Μουσικός, Τραγουδιστής",
    treatment: "Φυσικοθεραπεία",
    content: "Ο γνωστός Ψαραντώνης",
    rating: 5,
    date: "2023-04-15",
    imageUrl: "/gallery/testimonials/1a.jpg",
  },
  {
    id: "9",
    name: "Βασίλης Δοσούλας",
    profession: "Καλλιτέχνης",
    treatment: "Μακροχρόνια Αποκατάσταση",
    content: "Με τον αγαπημένο Βασίλη Δοσούλα, που μείναμε σχεδόν 3 χρόνια μαζί κάνοντας αποκατάσταση μετά τον σοβαρό του τραυματισμό",
    rating: 5,
    date: "2023-03-10",
    imageUrl: "/gallery/testimonials/dosoulas.jpg",
  },
  {
    id: "10",
    name: "Γιάννης Μωραΐτης",
    profession: "Μεγάλος δάσκαλος και θρύλος του μπουζουκιού",
    treatment: "Prolotherapy",
    content: "Με τον μεγάλο δάσκαλο και θρύλο του μπουζουκιού Γιάννη Μωραΐτη",
    rating: 5,
    date: "2023-02-28",
    imageUrl: "/gallery/testimonials/unfffgtitled-1.png",
  },
  {
    id: "11",
    name: "Νίκος Ξυδάκης",
    profession: "Μεγάλος Συνθέτης",
    treatment: "Ολιστική Θεραπεία",
    content: "Με τον μεγάλο μας Συνθέτη Νίκο Ξυδάκη",
    rating: 5,
    date: "2023-01-20",
    imageUrl: "/gallery/testimonials/ungfhhtitled-1.jpg",
  },
  {
    id: "12",
    name: "Φωτεινή Βελεσιώτου",
    profession: "Τραγουδίστρια",
    treatment: "Αποκατάσταση",
    content: "Με την Φωτεινή Βελεσιώτου",
    rating: 5,
    date: "2022-12-15",
    imageUrl: "/gallery/testimonials/martiriess4.jpg",
  },
  {
    id: "13",
    name: "Ασθενής",
    profession: "",
    treatment: "Προλοθεραπεία",
    content: "Χρόνιος πόνος χαμηλά στη μέση - Προλοθεραπεία",
    rating: 5,
    date: "2023-06-15",
    videoUrl: "5Er1w5w_JYg",
  },
  {
    id: "14",
    name: "Ασθενής",
    profession: "",
    treatment: "Θεραπεία πόνου γόνατος",
    content: "Θεραπεία πόνου στο γόνατο",
    rating: 5,
    date: "2023-05-10",
    videoUrl: "2Fvvmv5ec5o",
  },
  {
    id: "15",
    name: "Ασθενής",
    profession: "",
    treatment: "Θεραπεία πόνου ώμου",
    content: "Χρόνιος πόνος στον ώμο",
    rating: 5,
    date: "2023-04-20",
    videoUrl: "IhQVkBxSVzg",
  },
  {
    id: "16",
    name: "Ασθενής",
    profession: "",
    treatment: "Θεραπεία περιαρθρίτιδας",
    content: "Χρόνιος πόνος στον ώμο",
    rating: 5,
    date: "2023-03-15",
    videoUrl: "SlFAxOqF74U",
  },
  {
    id: "17",
    name: "Ασθενής",
    profession: "",
    treatment: "Θεραπεία χρόνιου πόνου",
    content: "Χρόνιος Πόνος 2",
    rating: 5,
    date: "2023-02-10",
    videoUrl: "3i1-Fcz56-0",
  },
];